name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create Binary
        run: npx @yao-pkg/pkg --out-path release dist/envify.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List files in release directory
        run: ls -l release

      - name: Print contents of binary directory
        run: ls -l ./release/envify-linux

      - name: Print GitHub token
        run: echo ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Release
        uses: TheAhmedGad/push-to-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          binary-path: ./release/envify-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
