name: Build and Release

on:
  push:
    branches: 
      - main
      
jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Create Binary
      run: npx @yao-pkg/pkg --target=node20-linux-x64 --out-path release dist/envify.js 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: minor

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release/envify-linux
        asset_name: envify
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
