name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Create Release
      run: npx @yao-pkg/pkg --out-path release dist/envify.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
