name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create Binary
        run: npx @yao-pkg/pkg --out-path release dist/envify.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: Shopify/upload-to-release@v2.0.0
        with:
          name: envify
          path: release/envify-linux
          repo-token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Upload binaries to release
#        uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "latest"
#          prerelease: false
#          title: "Latest Build"
#          files: |
#            release/envify-linux
#
#      - name: Upload binaries to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: release/envify-linux
#          asset_name: envify
#          tag: ${{ github.ref }}
#          overwrite: true
#          body: ${{ github.ref }}
