name: Build and Release

on:
  push:
    tags:
      - '*'
      
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Create Binary
      run: npx @yao-pkg/pkg --out-path release dist/envify.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release/envify-linux
        asset_name: envify
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
